# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from dggs_api_server.models.base_model_ import Model
from dggs_api_server.models.link import Link  # noqa: F401,E501
from dggs_api_server import util


class DggsList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, links: List[Link]=None):  # noqa: E501
        """DggsList - a model defined in Swagger

        :param links: The links of this DggsList.  # noqa: E501
        :type links: List[Link]
        """
        self.swagger_types = {
            'links': List[Link]
        }

        self.attribute_map = {
            'links': 'links'
        }
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'DggsList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The dggs-list of this DggsList.  # noqa: E501
        :rtype: DggsList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self) -> List[Link]:
        """Gets the links of this DggsList.

        The list of links to the DGGS Resource Specifications implemented by this OGC API Server.  # noqa: E501

        :return: The links of this DggsList.
        :rtype: List[Link]
        """
        return self._links

    @links.setter
    def links(self, links: List[Link]):
        """Sets the links of this DggsList.

        The list of links to the DGGS Resource Specifications implemented by this OGC API Server.  # noqa: E501

        :param links: The links of this DggsList.
        :type links: List[Link]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links
