# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from dggs_api_server.models.base_model_ import Model
from dggs_api_server import util


class DggsRsZoneClassZoneExtentZoneErrorBudget(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, spatial_units: str=None, spatial_error_budget: float=None, temporal_units: str=None, temporal_error_budget: float=None):  # noqa: E501
        """DggsRsZoneClassZoneExtentZoneErrorBudget - a model defined in Swagger

        :param spatial_units: The spatial_units of this DggsRsZoneClassZoneExtentZoneErrorBudget.  # noqa: E501
        :type spatial_units: str
        :param spatial_error_budget: The spatial_error_budget of this DggsRsZoneClassZoneExtentZoneErrorBudget.  # noqa: E501
        :type spatial_error_budget: float
        :param temporal_units: The temporal_units of this DggsRsZoneClassZoneExtentZoneErrorBudget.  # noqa: E501
        :type temporal_units: str
        :param temporal_error_budget: The temporal_error_budget of this DggsRsZoneClassZoneExtentZoneErrorBudget.  # noqa: E501
        :type temporal_error_budget: float
        """
        self.swagger_types = {
            'spatial_units': str,
            'spatial_error_budget': float,
            'temporal_units': str,
            'temporal_error_budget': float
        }

        self.attribute_map = {
            'spatial_units': 'spatialUnits',
            'spatial_error_budget': 'spatialErrorBudget',
            'temporal_units': 'temporalUnits',
            'temporal_error_budget': 'temporalErrorBudget'
        }
        self._spatial_units = spatial_units
        self._spatial_error_budget = spatial_error_budget
        self._temporal_units = temporal_units
        self._temporal_error_budget = temporal_error_budget

    @classmethod
    def from_dict(cls, dikt) -> 'DggsRsZoneClassZoneExtentZoneErrorBudget':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The dggsRsZoneClass_zoneExtent_zoneErrorBudget of this DggsRsZoneClassZoneExtentZoneErrorBudget.  # noqa: E501
        :rtype: DggsRsZoneClassZoneExtentZoneErrorBudget
        """
        return util.deserialize_model(dikt, cls)

    @property
    def spatial_units(self) -> str:
        """Gets the spatial_units of this DggsRsZoneClassZoneExtentZoneErrorBudget.

        Units to define the spatial error budget  # noqa: E501

        :return: The spatial_units of this DggsRsZoneClassZoneExtentZoneErrorBudget.
        :rtype: str
        """
        return self._spatial_units

    @spatial_units.setter
    def spatial_units(self, spatial_units: str):
        """Sets the spatial_units of this DggsRsZoneClassZoneExtentZoneErrorBudget.

        Units to define the spatial error budget  # noqa: E501

        :param spatial_units: The spatial_units of this DggsRsZoneClassZoneExtentZoneErrorBudget.
        :type spatial_units: str
        """

        self._spatial_units = spatial_units

    @property
    def spatial_error_budget(self) -> float:
        """Gets the spatial_error_budget of this DggsRsZoneClassZoneExtentZoneErrorBudget.

        Spatial Error Budget  # noqa: E501

        :return: The spatial_error_budget of this DggsRsZoneClassZoneExtentZoneErrorBudget.
        :rtype: float
        """
        return self._spatial_error_budget

    @spatial_error_budget.setter
    def spatial_error_budget(self, spatial_error_budget: float):
        """Sets the spatial_error_budget of this DggsRsZoneClassZoneExtentZoneErrorBudget.

        Spatial Error Budget  # noqa: E501

        :param spatial_error_budget: The spatial_error_budget of this DggsRsZoneClassZoneExtentZoneErrorBudget.
        :type spatial_error_budget: float
        """

        self._spatial_error_budget = spatial_error_budget

    @property
    def temporal_units(self) -> str:
        """Gets the temporal_units of this DggsRsZoneClassZoneExtentZoneErrorBudget.

        Units to define the temporal error budget  # noqa: E501

        :return: The temporal_units of this DggsRsZoneClassZoneExtentZoneErrorBudget.
        :rtype: str
        """
        return self._temporal_units

    @temporal_units.setter
    def temporal_units(self, temporal_units: str):
        """Sets the temporal_units of this DggsRsZoneClassZoneExtentZoneErrorBudget.

        Units to define the temporal error budget  # noqa: E501

        :param temporal_units: The temporal_units of this DggsRsZoneClassZoneExtentZoneErrorBudget.
        :type temporal_units: str
        """

        self._temporal_units = temporal_units

    @property
    def temporal_error_budget(self) -> float:
        """Gets the temporal_error_budget of this DggsRsZoneClassZoneExtentZoneErrorBudget.

        Temporal Error Budget  # noqa: E501

        :return: The temporal_error_budget of this DggsRsZoneClassZoneExtentZoneErrorBudget.
        :rtype: float
        """
        return self._temporal_error_budget

    @temporal_error_budget.setter
    def temporal_error_budget(self, temporal_error_budget: float):
        """Sets the temporal_error_budget of this DggsRsZoneClassZoneExtentZoneErrorBudget.

        Temporal Error Budget  # noqa: E501

        :param temporal_error_budget: The temporal_error_budget of this DggsRsZoneClassZoneExtentZoneErrorBudget.
        :type temporal_error_budget: float
        """

        self._temporal_error_budget = temporal_error_budget
