# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from dggs_api_server.models.base_model_ import Model
from dggs_api_server.models.link import Link  # noqa: F401,E501
from dggs_api_server import util


class LandingPageLink(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, links: List[Link]=None):  # noqa: E501
        """LandingPageLink - a model defined in Swagger

        :param links: The links of this LandingPageLink.  # noqa: E501
        :type links: List[Link]
        """
        self.swagger_types = {
            'links': List[Link]
        }

        self.attribute_map = {
            'links': 'links'
        }
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'LandingPageLink':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The landingPage-link of this LandingPageLink.  # noqa: E501
        :rtype: LandingPageLink
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self) -> List[Link]:
        """Gets the links of this LandingPageLink.


        :return: The links of this LandingPageLink.
        :rtype: List[Link]
        """
        return self._links

    @links.setter
    def links(self, links: List[Link]):
        """Sets the links of this LandingPageLink.


        :param links: The links of this LandingPageLink.
        :type links: List[Link]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links
