# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from dggs_api_server.models.base_model_ import Model
from dggs_api_server import util


class Trs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    HTTP_WWW_OPENGIS_NET_DEF_UOM_ISO_8601_0_GREGORIAN = "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"
    def __init__(self):  # noqa: E501
        """Trs - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Trs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The trs of this Trs.  # noqa: E501
        :rtype: Trs
        """
        return util.deserialize_model(dikt, cls)
