# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.feature_geo_json import FeatureGeoJSON  # noqa: F401,E501
from swagger_server.models.geometry_geo_json import GeometryGeoJSON  # noqa: F401,E501
from swagger_server.models.link import Link  # noqa: F401,E501
from swagger_server import util


class ZoneGeoJSON(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, geometry: GeometryGeoJSON=None, properties: object=None, id: Object=None, links: List[Link]=None, resolution: float=None):  # noqa: E501
        """ZoneGeoJSON - a model defined in Swagger

        :param type: The type of this ZoneGeoJSON.  # noqa: E501
        :type type: str
        :param geometry: The geometry of this ZoneGeoJSON.  # noqa: E501
        :type geometry: GeometryGeoJSON
        :param properties: The properties of this ZoneGeoJSON.  # noqa: E501
        :type properties: object
        :param id: The id of this ZoneGeoJSON.  # noqa: E501
        :type id: Object
        :param links: The links of this ZoneGeoJSON.  # noqa: E501
        :type links: List[Link]
        :param resolution: The resolution of this ZoneGeoJSON.  # noqa: E501
        :type resolution: float
        """
        self.swagger_types = {
            'type': str,
            'geometry': GeometryGeoJSON,
            'properties': object,
            'id': Object,
            'links': List[Link],
            'resolution': float
        }

        self.attribute_map = {
            'type': 'type',
            'geometry': 'geometry',
            'properties': 'properties',
            'id': 'id',
            'links': 'links',
            'resolution': 'resolution'
        }
        self._type = type
        self._geometry = geometry
        self._properties = properties
        self._id = id
        self._links = links
        self._resolution = resolution

    @classmethod
    def from_dict(cls, dikt) -> 'ZoneGeoJSON':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The zoneGeoJSON of this ZoneGeoJSON.  # noqa: E501
        :rtype: ZoneGeoJSON
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ZoneGeoJSON.


        :return: The type of this ZoneGeoJSON.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ZoneGeoJSON.


        :param type: The type of this ZoneGeoJSON.
        :type type: str
        """
        allowed_values = ["Feature"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def geometry(self) -> GeometryGeoJSON:
        """Gets the geometry of this ZoneGeoJSON.


        :return: The geometry of this ZoneGeoJSON.
        :rtype: GeometryGeoJSON
        """
        return self._geometry

    @geometry.setter
    def geometry(self, geometry: GeometryGeoJSON):
        """Sets the geometry of this ZoneGeoJSON.


        :param geometry: The geometry of this ZoneGeoJSON.
        :type geometry: GeometryGeoJSON
        """
        if geometry is None:
            raise ValueError("Invalid value for `geometry`, must not be `None`")  # noqa: E501

        self._geometry = geometry

    @property
    def properties(self) -> object:
        """Gets the properties of this ZoneGeoJSON.


        :return: The properties of this ZoneGeoJSON.
        :rtype: object
        """
        return self._properties

    @properties.setter
    def properties(self, properties: object):
        """Sets the properties of this ZoneGeoJSON.


        :param properties: The properties of this ZoneGeoJSON.
        :type properties: object
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")  # noqa: E501

        self._properties = properties

    @property
    def id(self) -> Object:
        """Gets the id of this ZoneGeoJSON.


        :return: The id of this ZoneGeoJSON.
        :rtype: Object
        """
        return self._id

    @id.setter
    def id(self, id: Object):
        """Sets the id of this ZoneGeoJSON.


        :param id: The id of this ZoneGeoJSON.
        :type id: Object
        """

        self._id = id

    @property
    def links(self) -> List[Link]:
        """Gets the links of this ZoneGeoJSON.


        :return: The links of this ZoneGeoJSON.
        :rtype: List[Link]
        """
        return self._links

    @links.setter
    def links(self, links: List[Link]):
        """Sets the links of this ZoneGeoJSON.


        :param links: The links of this ZoneGeoJSON.
        :type links: List[Link]
        """

        self._links = links

    @property
    def resolution(self) -> float:
        """Gets the resolution of this ZoneGeoJSON.


        :return: The resolution of this ZoneGeoJSON.
        :rtype: float
        """
        return self._resolution

    @resolution.setter
    def resolution(self, resolution: float):
        """Sets the resolution of this ZoneGeoJSON.


        :param resolution: The resolution of this ZoneGeoJSON.
        :type resolution: float
        """
        if resolution is None:
            raise ValueError("Invalid value for `resolution`, must not be `None`")  # noqa: E501

        self._resolution = resolution
